source 'https://rubygems.org'

# Pick a DB gem:
gem 'pg'
# gem 'mysql'

gem 'sequel'
gem 'bcrypt'
gem 'sinatra'
gem 'rspec'
gem 'rack-test'
gem 'factory_girl'

# Optional: Choose one:
# gem 'thin'
# gem 'unicorn'

# For debugging
gem 'byebug'
